### ISSUE TITLE
Linnet simple ABS bug on loading

### ISSUE THREAD

**Issue by Poryg1** [rafaelalmeidatk/JGSS#1]
There's an onload bug in Linnet simple ABS. Every game character object has a damageSpriteController on construction, However, due to the nature of how MV handles saves and loads. In short events' Damage_Sprite_Controllers get saved without their constructors, so they are loaded as generic Objects, losing all predefined methods, including the update method that gets called upon a character's update function, resulting in a crash.

**Comment by rafaelalmeidatk** [comment]
I don't work on these scripts anymore so I can't do a fix. I would like to mention that this ABS is very simple and is more for research than for official use.
